### ISSUE TITLE
Reorganizacao do sistema de pastas e projeto python como um todo

### ISSUE THREAD

**Issue by frmiza** [fga-eps-mds/2022-2-Squad06#56]
## Descrição
Reorganizar todo o backend e sistema de pastas do projeto python

## Tarefas
- [x] Deletar branch parser realizada a partir da main, ela devera ser associada ao brackend
- [x] Atualizar o projeto python e dependencias
- [x] Definir a cabeca da branch parser a partir da branch backend
- [x] Realizar o merge da branch parser 
- [x] Merge da branch backend na main com as novas modificacoes

## Critérios de Aprovação
- Merges realizados corretamente
- Branchs deletadas, as que forem necessarias
